// ---------------------------------------------------------------------------
// GeneratingInferences.java 
//
// $Id: GeneratingInferences.java,v 1.3 2026/04/14 12:32:59 schreine Exp $
//
// Author: Viktoria Langenreither <viki.langi@gmail.com>
// Copyright (C) 2023-, Research Institute for Symbolic Computation (RISC)
// Johannes Kepler University, Linz, Austria, https://www.risc.jku.at
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General public final License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General public final License for more details.
//
// You should have received a copy of the GNU General public final License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
// ----------------------------------------------------------------------------
package risctp.res;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import risctp.fol.*;
import risctp.syntax.AST.Exp.Not;
import risctp.types.Symbol;
import risctp.types.Symbol.FunctionSymbol;
import risctp.types.Symbol.VariableSymbol;

public class GeneratingInferences
{
  // the PureEquation
  public PureEquation GenInf;

  // the equality and inequality function symbol
  public FunctionSymbol eq;
  public FunctionSymbol neq;

  //ordering of the function/constant symbols used for the lexicographic path ordering
  public List<FunctionSymbol> ordering;

  // create a new SimplifyingInferences from a PureEquation
  public GeneratingInferences(PureEquation problem, FunctionSymbol eq, FunctionSymbol neq, List<FunctionSymbol> ordering)
  {
    this.GenInf = problem;
    this.eq = eq;
    this.neq = neq;
    this.ordering = ordering;
  }

  /**************************************************************************
   * Computes the equality resolvent of a clause given a unifier and a position.
   * The preconditions for applying this rule (as well as the unifier and the position)
   * have to be checked/computed in advance.
   * @param clause - the PureEquation s != t v R
   * @param subst - the unifier sigma = mgu(s, t)
   * @param pos - position of the literal s != t used to compute the equality resolvent 
   * @return the newly generated PureEquation generated by equality resolution sigma(R)
   *************************************************************************/
  public PureEquation computeEqResolvent(PureEquation clause, Subst subst, int pos)
  {
    List<Object> lits = new ArrayList<Object>();
    for (Object c : clause.lits) if (c != clause.lits[pos]) lits.add(c);

    int litn = lits.size();
    Object[] lits0 = new Object[litn];
    for (int i = 0; i < litn; i++) lits0[i] = (Object[]) subst.apply(lits.get(i));

    boolean[] negs = new boolean[litn];
    for (int i = 0; i < litn; i++)
    {
      if (lits0[i] instanceof Not) negs[i] = true;
      else negs[i] = false;
    }

    List<PureEquation> parents = new ArrayList<>();
    parents.add(clause);

    PureEquation rule = new PureEquation(clause.name, PureEquation.clauseCounter, clause.vars, lits0, negs,
        clause.selectionFunction(lits0, negs), clause.score, clause.age, "ER", parents, clause.marked);
    PureEquation.clauseCounter = PureEquation.clauseCounter + 1;
    return rule;	
  }

  //----------------------------------------------------------------------------
  //----------------------------------------------------------------------------
  public boolean eligibleForResolution(PureEquation clause, Subst sigma, Object l)
  {
    List<Integer> selected = clause.select;

    List<Object> sel = new ArrayList<Object>();
    List<Object> cpos = new ArrayList<Object>();
    List<Object> cneg = new ArrayList<Object>();
    List<Object> intersecpos = new ArrayList<Object>();
    List<Object> intersecneg = new ArrayList<Object>();

    for(int i : selected) sel.add(clause.lits[i]);

    for(Object lit : clause.lits)
    {
      if(lit instanceof Not) cneg.add(lit);
      else cpos.add(lit);
    }

    for(Object lit : sel)
    {
      if (cpos.contains(lit)) intersecpos.add(lit);
      if (cneg.contains(lit)) intersecneg.add(lit);
    }

    List<Object> lits = new ArrayList<>();
    for (Object c : clause.lits) lits.add(c);

    if(selected.isEmpty() && maximality(lits, sigma, l)) return true;
    if(selected.isEmpty() == false && maximality(intersecneg, sigma, l)) return true;
    if(selected.isEmpty() == false && maximality(intersecpos, sigma, l)) return true;

    return false;
  }

  // Returns true, if literal l the maximal literal in clause according to LPO
  public boolean maximality(List<Object> clause, Subst sigma, Object l)
  {
    l = sigma.apply(l);

    // if a clause only contains one literal, this literal is maximal in this clause
    if(clause.size() == 1) return true;

    for (Object lit : clause)
    {
      Object sigmac = sigma.apply(lit);
      if (Term.equal(sigmac, l) == false)
      {
        if (PureEquation.lpo(sigmac, l, ordering) == true) return false;
      } 
    }
    return true;
  }

  /**************************************************************************
   * Computes all possible equality resolvent of a clause (the givenclause).
   * Every literal gets checks if it fulfills the preconditions.
   * @param givenclause - the PureEquation 
   * @return list of all newly generated equality resolvents
   *************************************************************************/
  public List<PureEquation> computeAllEqResolvents(PureEquation givenclause)
  {
    List<PureEquation> t =  new ArrayList<>();
    List<Object> lits =  new ArrayList<>();
    for (Object c : givenclause.lits) lits.add(c);

    for(int i = 0; i < lits.size(); i++)
    {		
      if (givenclause.negs[i] == true)
      {
        Subst sigma = new Subst();
        boolean unify = Subst.unify(sigma, Term.argument(lits.get(i), 0),
            Term.argument(lits.get(i), 1));
        if (unify == true)
        {
          Object sigmal = sigma.apply(lits.get(i));
          boolean test = eligibleForResolution(givenclause, sigma, sigmal);
          if (test == true) t.add(computeEqResolvent(givenclause, sigma, i));	
        }
      }
    }
    return t;
  }

  //----------------------------------------------------------------------------
  // Returns true, if the criterion for "eligibility for paramodulation" if fulfilled
  // 
  //----------------------------------------------------------------------------
  public boolean eligibleForParamodulation(PureEquation clause, Subst sigma, Object l)
  {
    List<Object> sigmac = new ArrayList<>();
    if (maximality(sigmac, sigma, sigma.apply(l))) return true;
    return false;
  }

  /**************************************************************************
   * Computes the equality factor of a clause given a unifier and a position.
   * The preconditions for applying this rule (+ the unifier and the positions)
   * have to be checked/computed in advance.
   * @param clause - the PureEquation s = t V u = v V R
   * @param subst - the unifier sigma = mgu(s, u)
   * @param pos1 - position of the literal s = t used to compute the equality factor
   * @param pos2 - position of the literal u = v used to compute the equality factor 
   * @return the newly generated PureEquation generated by equality factor
   *         sigma(t != u V u = v V R)
   *************************************************************************/
  public PureEquation computeEqualityFactor(PureEquation clause, Subst sigma,
    int pos1, int pos2)
  {
    List<Object> lits = new ArrayList<>();
    for (Object l : clause.lits) lits.add(l);
    int litn = lits.size();

    boolean[] negs = new boolean[litn];
    for (int i = 0; i < litn; i++) negs[i] = clause.negs[i];

    Object[] args = new Object[2];
    args[0] = Term.argument(lits.get(pos1), 1);
    args[1] = Term.argument(lits.get(pos2), 1);  

    lits.set(pos1, Term.term(neq, args));
    negs[pos1] = true;

    Object[] lits0 = new Object[litn];
    for (int i = 0; i < litn; i++) lits0[i] = sigma.apply(lits.get(i));

    List<PureEquation> parents = new ArrayList<>();
    parents.add(clause);

    PureEquation returnclause = new PureEquation(clause.name,
        PureEquation.clauseCounter, clause.vars, lits0, negs, clause.select,
        clause.score, clause.age, "EF", parents, clause.marked);
    PureEquation.clauseCounter = PureEquation.clauseCounter + 1;
    return returnclause;
  }

  /**************************************************************************
   * Computes all possible equality factory of a clause (the givenclause).
   * Every literal gets checks if it fulfills the preconditions.
   * @param givenclause - the PureEquation 
   * @return list of all newly generated equality factors
   *************************************************************************/
  public List<PureEquation> equalityFactoring(PureEquation givenclause)
  {
    List<PureEquation> t =  new ArrayList<>();
    List<Object> lits = new ArrayList<Object>();
    for (Object c : givenclause.lits) lits.add(c);
    boolean[] negs = givenclause.negs;
    List<Integer> selected = givenclause.select;
    if (selected.isEmpty() == true)
    {
      for (int i = 0; i < lits.size()-1; i ++)
      {
        if(negs[i] == false)
        {		  
          for (int j = i+1; j < lits.size(); j ++)
          {
            if (negs[j] == false)
            {
              Subst sigma = new Subst();
              boolean unify = Subst.unify(sigma, Term.argument(lits.get(i), 0),
                  Term.argument(lits.get(j), 0));		  
              if (unify == true)
              {
                boolean test1 = false;
                Object lit = lits.get(i);
                Object s0 = sigma.apply(Term.argument(lit, 0));
                Object t0 = sigma.apply(Term.argument(lit, 1));
                if (PureEquation.lpo(t0, s0, ordering) == false) test1 = true;  
                boolean test2 = eligibleForParamodulation(givenclause, sigma,
                    lits.get(i));			  
                if(test1 == true && test2 == true)
                  t.add(computeEqualityFactor(givenclause, sigma, i, j));
              }
            }
          }
        }
      }
    }
    return t;
  }

  /**************************************************************************
   * Computes the new clause according to the superposition inference rule of two 
   * clauses given two positions, a unifier and the note if it is superposition into 
   * positive or of negative literals.
   * The preconditions for applying this rule (as well as the unifier and the positions)
   * have to be checked/computed in advance.
   * @param clause1 - PureEquation s = t V S
   * @param pos1 - position of the literal that superposition can be applied to
   * @param givenclause - the given clause u = v V R respectively u != v V R 
   * @param pos2 - position of the literal that superposition can be applied to
   * @param sigma - the unifier sigma = mgu(u|p, s)
   * @param p - position of the term in u superposition can be applied to
   * @param posneg - string, indicating to use positive or negative superposition 
   * @param newlit - newly constructed literal if the rule gets applied to an inner term of u
   * @return the newly generated PureEquation generated by superposition sigma(u[p <-- t] != v V S V R)
   *************************************************************************/
  public PureEquation computeSuperpositionPositiveLiteral(PureEquation clause1, int pos1, PureEquation givenclause,
    int pos2, Subst sigma, int p, String posneg, Object newlit)
  {
    List<Object> lits = new ArrayList<Object>();
    for (Object c : givenclause.lits) lits.add(c);  
    Object remove = clause1.lits[pos1];
    for (Object c : clause1.lits) if (c != remove) lits.add(c);
    int n = givenclause.negs.length;
    boolean[] negs = new boolean[n + clause1.negs.length - 1];
    for (int i = 0; i < n; i++) negs[i] = givenclause.negs[i];
    int j = 0;
    for (int i = 0; i < clause1.negs.length; i++)
    {
      if (i != pos1)
      {
        negs[n+j] = clause1.negs[i];
        j++;
      }
    }
    Object t = Term.argument(remove, 1);
    int litn = lits.size();
    Object[] args = new Object[2];
    if (p == -1) args[0] = t;
    else
    {
      args[0] = Term.argument(newlit, 0);
    }
    String generatedby = "";
    args[1] = Term.argument(lits.get(pos2), 1);  
    if (posneg == "positiv")
    {
      lits.set(pos2, Term.term(eq, args));
      generatedby = "SP";
    }
    else if (posneg == "negativ")
    {
      lits.set(pos2, Term.term(neq, args));
      generatedby = "SN";
    } 
    Object[] lits0 = new Object[litn];
    for (int i = 0; i < litn; i++) lits0[i] = sigma.apply(lits.get(i));

    int len1 = givenclause.vars.length;
    int len2 = clause1.vars.length; 
    VariableSymbol[] vars0 = new VariableSymbol[len1 + len2];

    for (int i = 0; i < len1; i++) vars0[i] = givenclause.vars[i];
    for (int i = 0; i < len2; i++) vars0[i+len1] = clause1.vars[i];

    List<PureEquation> parents = new ArrayList<>();
    parents.add(clause1);
    parents.add(givenclause);

    PureEquation returnclause = new PureEquation(givenclause.name, PureEquation.clauseCounter, vars0, lits0, negs,
        givenclause.select, givenclause.score, givenclause.age, generatedby, parents, givenclause.marked);
    PureEquation.clauseCounter = PureEquation.clauseCounter + 1;
    return returnclause;
  }

  /**************************************************************************
   * Computes all possible superpositions of the given clause and the processed clauses
   * Every clause (and literal) gets checks if it fulfills the preconditions.
   * @param givenclause - the given clause u = v V R respectively u != v V R
   * @param processed - list of processed PureEquations (possible inference partners)
   * @return list of all newly generated clauses (with superposition)
   *************************************************************************/
  //given clause is the right-hand clause in the inference rule
  public List<PureEquation> superpositionIntoPositiveLiterals(PureEquation givenclause,
    List<PureEquation> processed)
  {  
    List<PureEquation> t =  new ArrayList<>();
    String posneg;
    List<Object> lits = new ArrayList<Object>();
    for (Object c : givenclause.lits) lits.add(c);
    int j = 0;
    int i = 0;
    for (Object l1 : lits)
    {
      Object u = Term.argument(l1, 0);
      Object v = Term.argument(l1, 1);
      if (givenclause.negs[i] == false) posneg = "positiv";
      else posneg = "negativ";
      for (PureEquation clause : processed)
      { //with every clause in processed we try to generate a new one
        j = 0;
        for (Object l2 : clause.lits)
        {
          if (clause.negs[j] == false)
          { //in left clause has to be an equality	  
            if ((u instanceof VariableSymbol) == false)
            { // u at position p is not allowed to be a variable
              Subst sigma = new Subst();
              boolean unify = Subst.unify(sigma, u, Term.argument(l2, 0));
              if (unify == true)
              { 
                if (PureEquation.lpo(Term.argument(l2, 1), Term.argument(l2, 0), ordering)
                    == false)
                {
                  if (PureEquation.lpo(v, u, ordering) == false)
                  {
                    if (eligibleForParamodulation(clause, sigma, l2) == true)
                    {
                      if (eligibleForResolution(givenclause, sigma, l1) == true)
                      {
                        t.add(computeSuperpositionPositiveLiteral(clause, j, givenclause, i,
                            sigma, -1, posneg, ""));
                      }
                    }
                  }
                }
              }
              j++;
              continue;
            }	  
          }
          j++;
        }
      }
      i++;
    }  
    return t;
  }

  //----------------------------------------------------------------------------


  //----------------------------------------------------------------------------

  // given clause is the right-hand clause in the inference rule
  public List<PureEquation> superpositionIntoPositiveLiteralsInnerTerms(PureEquation givenclause, PureEquation clause, Object lit,
    Object subterm, int i, Function<Object, Object> overwrite)
  {  
    List<PureEquation> t =  new ArrayList<>();
    String posneg;

    int j = 0;
    Object u = Term.argument(lit, 0);
    Object v = Term.argument(lit, 1);
    if (givenclause.negs[i] == false) posneg = "positiv";
    else posneg = "negativ";
    j = 0; // position of the literal in clause
    for (Object l2 : clause.lits) // left side of l2 is s
    {
      if (clause.negs[j] == false)
      { //in left clause has to be an equality	    
        for (int p = 0; p < Term.argnumber(subterm); p++)
        {
          final int i0 = p;
          Object up = Term.argument(subterm, p); 
          if ((up instanceof VariableSymbol) == false)
          { // u at position p is not allowed to be a variable
            Subst sigma = new Subst();
            boolean unify = Subst.unify(sigma, up, Term.argument(l2, 0));
            if (unify == true)
            { 
              if (PureEquation.lpo(Term.argument(l2, 1), Term.argument(l2, 0), ordering) == false)
              {
                if (PureEquation.lpo(v, u, ordering) == false)
                {
                  if (eligibleForParamodulation(clause, sigma, l2) == true)
                  {
                    if (eligibleForResolution(givenclause, sigma, lit) == true)
                    {

                      Object t_term = Term.argument(l2, 1); // right side of l2 is t
                      Object t0 = overwrite.apply(t_term);

                      Object[] args = new Object[2];
                      args[0] = t0;
                      args[1] = v;

                      Object new_lit;
                      if (givenclause.negs[i] == true) new_lit = Term.term(neq, args);
                      else new_lit = Term.term(eq, args);

                      t.add(computeSuperpositionPositiveLiteral(clause, j, givenclause, i, sigma, p, posneg, new_lit));
                    }
                  }
                }
              }
            }
          }
          // recursive call
          if (Term.symbol(u) instanceof VariableSymbol) continue;
          int n = Term.argnumber(u);
          FunctionSymbol fun = (FunctionSymbol)Term.symbol(u);

          Function<Object,Object> overwrite0 = (Object term0)->
          {
            Object[] terms0 = new Object[n];
            for (int l = 0; l < n; l++)
            {
              if (l == i0)
                terms0[l] = term0;
              else
                terms0[l] = Term.argument(u, l);
            }
            Object term1 = Term.term(fun, terms0);
            Object term2 = overwrite.apply(term1);
            return term2;
          };
          Symbol sym = Term.symbol(up);
          if (sym instanceof FunctionSymbol)
          {
            if (Term.argnumber(up) == 0) return t;
            else t.addAll(superpositionIntoPositiveLiteralsInnerTerms(givenclause, clause, lit, up, i, overwrite0));
          }
        }
      }
      j++;
    }
    return t;
  }

  /**************************************************************************
   * Computes all possible new clauses between the givenclause and the processed clauses
   * using superposition
   * Computes superposition (if possible) using the given clause as as the left hand
   * clause and then using the given clause as the right hand clause
   * runs trough all processed clauses
   * @param givenclause
   * @return list of all newly generated clauses (with superposition)
   *************************************************************************/
  public List<PureEquation> superposition(PureEquation givenclause,
    List<PureEquation> processed)
  {  
    List<PureEquation> t =  new ArrayList<>();
    List<PureEquation> givenclauselist =  new ArrayList<>();
    givenclauselist.add(givenclause);  
    t.addAll(superpositionIntoPositiveLiterals(givenclause, processed));

    List<Object> lits = new ArrayList<Object>();
    for (Object c : givenclause.lits) lits.add(c);
    int i = 0;
    int j = 0;

    for (PureEquation clause : processed)
    {
      i = 0;
      t.addAll(superpositionIntoPositiveLiterals(clause, givenclauselist));
      for (Object lit : lits)
      {
        Function<Object,Object> overwrite = (Object t0)->t0;
        t.addAll(superpositionIntoPositiveLiteralsInnerTerms(givenclause, clause,
            lit, givenclause.lits[i], i, overwrite));
        i++;
      }
    }

    for (PureEquation clause : processed)
    {
      j = 0;
      List<Object> lits2 = new ArrayList<Object>();
      for (Object c : clause.lits) lits2.add(c);
      for (Object lit : lits2)
      {
        Function<Object,Object> overwrite = (Object t0)->t0;
        t.addAll(superpositionIntoPositiveLiteralsInnerTerms(clause, givenclause,
            lit, clause.lits[j], j, overwrite));
        j++;
      }
    }

    return t;
  }

} // end class

// ----------------------------------------------------------------------------
// end of file
// ----------------------------------------------------------------------------
